"""empty message

Revision ID: 715c0a735807
Revises: e4d746d5a14e
Create Date: 2024-09-23 10:32:44.779250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715c0a735807'
down_revision = 'e4d746d5a14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
